/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/my_room4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/my_room4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WALL.geometry} material={nodes.WALL.material} position={[0.026, 9.965, 0]} />
      <mesh geometry={nodes.TV_TABLE.geometry} material={nodes.TV_TABLE.material} position={[19.204, 3.844, -8.207]} />
      <mesh geometry={nodes.TV.geometry} material={nodes.TV.material} position={[6.515, 9.466, -7.107]} rotation={[0.093, 0, 0]} />
      <mesh geometry={nodes.TABLE.geometry} material={nodes.TABLE.material} position={[-7.088, 5.324, -0.549]} />
      <mesh geometry={nodes.BOOK_SHELF_MIDDLE.geometry} material={nodes.BOOK_SHELF_MIDDLE.material} position={[-8.604, 9.237, 7.207]} />
      <mesh geometry={nodes.BOOK_SHELF_TOP.geometry} material={nodes.BOOK_SHELF_TOP.material} position={[-8.604, 11.173, 7.872]} />
      <mesh geometry={nodes.BOOK_SHELF_LOWER.geometry} material={nodes.BOOK_SHELF_LOWER.material} position={[-8.604, 7.154, 7.872]} />
      <mesh geometry={nodes.GRABAGE.geometry} material={nodes.GRABAGE.material} position={[-7.39, 1.707, 7.724]} />
      <mesh geometry={nodes.MonitorArmBase.geometry} material={nodes.MonitorArmBase.material} position={[-8.937, 4.577, -2.415]} />
      <mesh geometry={nodes.RIGHT_MONITOR.geometry} material={nodes.RIGHT_MONITOR.material} position={[-8.393, 7.193, -3.485]} />
      <mesh geometry={nodes.MONITOR_FIX.geometry} material={nodes.MONITOR_FIX.material} position={[-8.464, 7.235, -3.424]} />
      <mesh geometry={nodes.MONITOR_RIGHT.geometry} material={nodes.MONITOR_RIGHT.material} position={[-8.356, 6.949, 0.161]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.MONITOR_FIX2.geometry} material={nodes.MONITOR_FIX2.material} position={[-8.427, 6.888, -0.358]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.GARBAGE_PEDAL.geometry} material={nodes.GARBAGE_PEDAL.material} position={[-6.57, 0.737, 7.735]} />
      <mesh geometry={nodes.KEYBOARD_PAD.geometry} material={nodes.KEYBOARD_PAD.material} position={[-6.242, 4.549, -0.625]} />
      <mesh geometry={nodes.NOTEBOOK_STAND3.geometry} material={nodes.NOTEBOOK_STAND3.material} position={[-7.524, 4.654, 3.78]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.NOTEBOOK.geometry} material={nodes.NOTEBOOK.material} position={[-7.489, 5.205, 3.868]} rotation={[0, 0, -0.681]} />
      <mesh geometry={nodes.KEYBOARD_HOUSING.geometry} material={nodes.KEYBOARD_HOUSING.material} position={[-6.211, 4.663, -0.069]} />
      <mesh geometry={nodes.MAGICPAD.geometry} material={nodes.MAGICPAD.material} position={[-6.021, 4.583, -3.035]} rotation={[0, 0, 0.067]} />
      <mesh geometry={nodes.WALL_ALBUM.geometry} material={nodes.WALL_ALBUM.material} position={[-7.283, 10.282, -6.813]} />
      <mesh geometry={nodes.WALL_ALBUM2.geometry} material={nodes.WALL_ALBUM2.material} position={[-4.646, 10.282, -6.813]} />
      <mesh geometry={nodes.ALBUM_LIGHT.geometry} material={nodes.ALBUM_LIGHT.material} position={[-5.815, 14.725, -2.985]} />
      <mesh geometry={nodes.TV_FIX.geometry} material={nodes.TV_FIX.material} position={[6.515, 9.466, -7.252]} rotation={[0.078, -0.01, -0.003]} />
      <mesh geometry={nodes.SPEAKER_RIGHT.geometry} material={nodes.SPEAKER_RIGHT.material} position={[12.467, 2.752, -7.312]} />
      <mesh geometry={nodes.SPEAKER_LEFT.geometry} material={nodes.SPEAKER_LEFT.material} position={[0.48, 2.752, -7.312]} />
      <mesh geometry={nodes.SETTOP.geometry} material={nodes.SETTOP.material} position={[9.835, 4.028, -7.442]} />
      <mesh geometry={nodes.REMOTE_CONTROLLER.geometry} material={nodes.REMOTE_CONTROLLER.material} position={[8.624, 3.949, -7.48]} />
      <mesh geometry={nodes.BOOK_1.geometry} material={nodes.BOOK_1.material} position={[-8.243, 7.999, 8.703]} />
      <mesh geometry={nodes.BOOK_2.geometry} material={nodes.BOOK_2.material} position={[-8.243, 7.999, 7.036]} />
      <mesh geometry={nodes.BOOK_3.geometry} material={nodes.BOOK_3.material} position={[-8.243, 10.098, 8.219]} />
      <mesh geometry={nodes.BOOK_4.geometry} material={nodes.BOOK_4.material} position={[-8.243, 10.098, 6.943]} rotation={[0.328, 0, 0]} />
      <mesh geometry={nodes.BOOK_5.geometry} material={nodes.BOOK_5.material} position={[-8.243, 12.015, 8.935]} />
      <mesh geometry={nodes.BOOK_6.geometry} material={nodes.BOOK_6.material} position={[-8.527, 11.397, 7.378]} rotation={[Math.PI / 2, 0, -0.47]} />
      <mesh geometry={nodes.BOOK_7.geometry} material={nodes.BOOK_7.material} position={[-8.527, 11.702, 7.378]} rotation={[Math.PI / 2, 0, 0.41]} />
      <mesh geometry={nodes.CHAIR.geometry} material={nodes.CHAIR.material} position={[-1.095, 3.348, -0.854]} rotation={[0, 0.611, 0]} scale={[1.198, 0.114, 1.091]} />
      <mesh geometry={nodes.IPHONE.geometry} material={nodes.IPHONE.material} position={[-8.83, 4.919, -8.264]} scale={[1, 1, 0.782]} />
      <mesh geometry={nodes.PHONE_FIX.geometry} material={nodes.PHONE_FIX.material} position={[-8.742, 5.104, -8.212]} scale={[1, 1, 0.782]} />
      <mesh geometry={nodes.SOFA2.geometry} material={nodes.SOFA2.material} position={[8.472, 1.349, 5.234]} scale={[2.101, 0.558, 2.146]} />
    </group>
  )
}

useGLTF.preload('/my_room4.glb')
