/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/my_room.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/my_room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="WALL" geometry={nodes.WALL.geometry} material={materials.grey_wall} position={[0.026, 9.965, 0]} />
      <mesh name="TV_TABLE" geometry={nodes.TV_TABLE.geometry} material={materials.white} position={[19.204, 3.844, -8.207]} scale={[5.076, 0.167, 1.454]} />
      <group name="TV" position={[6.515, 9.466, -7.107]} rotation={[0.093, 0, 0]} scale={[5.774, 2.738, 0.061]}>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.black_tv} />
        <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.blakc_grey} />
      </group>
      <group name="TABLE" position={[-7.088, 5.324, -0.549]}>
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.white} />
        <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials.balck_fabric} />
      </group>
      <mesh name="BOOK_SHELF_MIDDLE" geometry={nodes.BOOK_SHELF_MIDDLE.geometry} material={materials.black_tv} position={[-8.604, 9.237, 7.207]} scale={[1, 0.1, 1.383]} />
      <mesh name="BOOK_SHELF_TOP" geometry={nodes.BOOK_SHELF_TOP.geometry} material={materials.black_tv} position={[-8.604, 11.173, 7.872]} scale={[1, 0.1, 1.383]} />
      <mesh name="BOOK_SHELF_LOWER" geometry={nodes.BOOK_SHELF_LOWER.geometry} material={materials.black_tv} position={[-8.604, 7.154, 7.872]} scale={[1, 0.1, 1.383]} />
      <mesh name="GRABAGE" geometry={nodes.GRABAGE.geometry} material={materials.garbage_grey} position={[-7.39, 1.707, 7.724]} scale={[0.827, 1.19, 0.827]} />
      <mesh name="MonitorArmBase" geometry={nodes.MonitorArmBase.geometry} material={materials.white} position={[-8.937, 4.577, -2.415]} scale={[0.377, 0.051, 0.718]} />
      <mesh name="RIGHT_MONITOR" geometry={nodes.RIGHT_MONITOR.geometry} material={materials.black_tv} position={[-8.393, 7.193, -3.485]} rotation={[-Math.PI, 0, 0]} scale={[-0.064, -1.917, -1.111]} />
      <mesh name="MONITOR_FIX" geometry={nodes.MONITOR_FIX.geometry} material={nodes.MONITOR_FIX.material} position={[-8.464, 7.235, -3.424]} scale={[0.036, 0.303, 0.381]} />
      <mesh name="MONITOR_RIGHT" geometry={nodes.MONITOR_RIGHT.geometry} material={materials.black_tv} position={[-8.356, 6.949, 0.161]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.064, -2.504, -1.072]} />
      <mesh name="MONITOR_FIX2" geometry={nodes.MONITOR_FIX2.geometry} material={nodes.MONITOR_FIX2.material} position={[-8.427, 6.888, -0.358]} rotation={[Math.PI / 2, 0, 0]} scale={[0.036, 0.303, 0.381]} />
      <mesh name="GARBAGE_PEDAL" geometry={nodes.GARBAGE_PEDAL.geometry} material={materials.black_tv} position={[-6.57, 0.737, 7.735]} scale={[-0.181, -0.031, -0.235]} />
      <mesh name="KEYBOARD_PAD" geometry={nodes.KEYBOARD_PAD.geometry} material={materials.white} position={[-6.242, 4.549, -0.625]} scale={[1.047, 1, 1]} />
      <group name="NOTEBOOK_STAND3" position={[-7.524, 4.654, 3.78]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.blakc_grey} />
        <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials.notebook_stand} />
      </group>
      <group name="NOTEBOOK" position={[-7.489, 5.205, 3.868]} rotation={[0, 0, -0.681]}>
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.notebook_hosuing} />
        <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials.black_tv} />
      </group>
      <mesh name="NOTEBOOK_TOPKEYBOARD" geometry={nodes.NOTEBOOK_TOPKEYBOARD.geometry} material={materials.black_tv} position={[-7.776, 5.477, 4.602]} rotation={[0, 0, -0.681]} scale={[0.048, 0.01, 0.048]} />
      <mesh name="NOTEBOOK_TOPKEYBOARD001" geometry={nodes.NOTEBOOK_TOPKEYBOARD001.geometry} material={materials.black_tv} position={[-7.852, 5.54, 3.868]} rotation={[0, 0, -0.681]} scale={[-0.031, -0.009, -0.781]} />
      <group name="KEYBOARD_HOUSING" position={[-6.211, 4.663, -0.069]} scale={[1.808, 0.081, 2.222]}>
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials.white} />
        <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials['grey.001']} />
      </group>
      <mesh name="MAGICPAD" geometry={nodes.MAGICPAD.geometry} material={materials.notebook_hosuing} position={[-6.021, 4.583, -3.035]} rotation={[0, 0, 0.067]} scale={[1.188, 1.001, 1]} />
      <group name="WALL_ALBUM" position={[-7.283, 10.282, -6.813]} rotation={[0, 0, -Math.PI]} scale={[-1.232, -1.661, -0.057]}>
        <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials.white} />
        <mesh name="Cube057_1" geometry={nodes.Cube057_1.geometry} material={materials.balck_fabric} />
      </group>
      <group name="WALL_ALBUM2" position={[-4.646, 10.282, -6.813]} rotation={[0, 0, -Math.PI]} scale={[-1.01, -1.363, -0.047]}>
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials.white} />
        <mesh name="Cube058_1" geometry={nodes.Cube058_1.geometry} material={materials.balck_fabric} />
      </group>
      <mesh name="ALBUM_LIGHT" geometry={nodes.ALBUM_LIGHT.geometry} material={materials.black_tv} position={[-5.815, 14.725, -2.985]} />
      <group name="CHAIR_FIX" position={[-0.17, 1.122, 0.059]} rotation={[0, 1.116, 0]}>
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.notebook_stand} />
        <mesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials.balck_fabric} />
      </group>
      <mesh name="TV_FIX" geometry={nodes.TV_FIX.geometry} material={materials.white} position={[6.515, 9.466, -7.252]} rotation={[0.078, -0.01, -0.003]} scale={[0.557, 0.553, 0.121]} />
      <group name="SPEAKER_RIGHT" position={[12.467, 2.752, -7.312]} scale={[0.721, 2.278, 1]}>
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.balck_fabric} />
        <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={materials.white} />
      </group>
      <group name="SPEAKER_LEFT" position={[0.48, 2.752, -7.312]} scale={[0.721, 2.278, 1]}>
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials.balck_fabric} />
        <mesh name="Cube028_1" geometry={nodes.Cube028_1.geometry} material={materials.white} />
      </group>
      <group name="SETTOP" position={[9.835, 4.028, -7.442]}>
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials.balck_fabric} />
        <mesh name="Cube029_1" geometry={nodes.Cube029_1.geometry} material={materials.white} />
      </group>
      <group name="REMOTE_CONTROLLER" position={[8.624, 3.949, -7.48]}>
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials.black_tv} />
        <mesh name="Cube036_1" geometry={nodes.Cube036_1.geometry} material={materials.red} />
        <mesh name="Cube036_2" geometry={nodes.Cube036_2.geometry} material={materials.yellow} />
        <mesh name="Cube036_3" geometry={nodes.Cube036_3.geometry} material={materials.green} />
        <mesh name="Cube036_4" geometry={nodes.Cube036_4.geometry} material={materials['blue.001']} />
        <mesh name="Cube036_5" geometry={nodes.Cube036_5.geometry} material={materials.orange} />
      </group>
      <mesh name="SOFA" geometry={nodes.SOFA.geometry} material={materials.balck_fabric} position={[7.337, 2.742, 4.96]} scale={[5.405, 2.521, 2.89]} />
      <group name="BOOK_1" position={[-8.243, 7.999, 8.703]} scale={[-0.534, -0.743, -0.26]}>
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials.white} />
        <mesh name="Cube040_1" geometry={nodes.Cube040_1.geometry} material={materials.deep_green} />
        <mesh name="Cube040_2" geometry={nodes.Cube040_2.geometry} material={materials.red} />
        <mesh name="Cube040_3" geometry={nodes.Cube040_3.geometry} material={materials.blue} />
      </group>
      <group name="BOOK_2" position={[-8.243, 7.999, 7.036]} scale={[-0.534, -0.743, -0.184]}>
        <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={materials.grey} />
        <mesh name="Cube062_1" geometry={nodes.Cube062_1.geometry} material={materials.white} />
      </group>
      <group name="BOOK_3" position={[-8.243, 10.098, 8.219]} scale={[-0.534, -0.743, -0.26]}>
        <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials.balck_fabric} />
        <mesh name="Cube063_1" geometry={nodes.Cube063_1.geometry} material={materials.deep_green} />
        <mesh name="Cube063_2" geometry={nodes.Cube063_2.geometry} material={materials.white} />
      </group>
      <group name="BOOK_4" position={[-8.243, 10.098, 6.943]} rotation={[0.328, 0, 0]} scale={[-0.534, -0.743, -0.184]}>
        <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials.blue} />
        <mesh name="Cube064_1" geometry={nodes.Cube064_1.geometry} material={materials.white} />
      </group>
      <group name="BOOK_5" position={[-8.243, 12.015, 8.935]} scale={[-0.534, -0.743, -0.207]}>
        <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={materials.blakc_grey} />
        <mesh name="Cube065_1" geometry={nodes.Cube065_1.geometry} material={materials.red} />
        <mesh name="Cube065_2" geometry={nodes.Cube065_2.geometry} material={materials.white} />
      </group>
      <group name="BOOK_6" position={[-8.527, 11.397, 7.378]} rotation={[Math.PI / 2, 0, -0.47]} scale={[-0.353, -0.557, -0.132]}>
        <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials['blue.001']} />
        <mesh name="Cube067_1" geometry={nodes.Cube067_1.geometry} material={materials.white} />
      </group>
      <group name="BOOK_7" position={[-8.527, 11.702, 7.378]} rotation={[Math.PI / 2, 0, 0.41]} scale={[-0.421, -0.664, -0.157]}>
        <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials.orange} />
        <mesh name="Cube068_1" geometry={nodes.Cube068_1.geometry} material={materials.white} />
      </group>
      <mesh name="CUSHION_1" geometry={nodes.CUSHION_1.geometry} material={materials.white} position={[5.418, 2.983, 5.581]} rotation={[1.634, 0.171, 2.998]} scale={[-1.629, -0.585, -1.259]} />
      <mesh name="CUSHION_2" geometry={nodes.CUSHION_2.geometry} material={materials.white} position={[9.078, 2.983, 5.504]} rotation={[-1.464, 0.108, -0.174]} scale={[-1.629, -0.585, -1.259]} />
    </group>
  )
}

useGLTF.preload('/my_room.glb')
